[[pages]]
path = "pages/0 - accueil.py"
name = "Accueil"
icon = "âš½"

[[pages]]
path = "pages/1 - similarite.py"
name = "Recherche d'un joueur similaire"
icon = "ğŸ‘¬ğŸ»"

[[pages]]
path = "pages/2 - ideal.py"
name = "Trouver le joueur idÃ©al"
icon = "ğŸ”"
